name: Docker args

on: [ push ]

concurrency:
  # seems to be a safe usage
  group: ${{ github.ref }}
  cancel-in-progress: true


jobs:
  create_commit:
    runs-on: ubuntu-18.04
    # env:
    steps:
      - name: Explain why this job ran
        uses: octo-org/action-name@main
        with:
          entrypoint: /bin/echo
          args: The ${{ github.event_name }} event triggered this step.
