# Test github.ref inside  `if: github.ref == 'refs/head/main' is executed at the shell level
name: Test command injection through `if` YAML directive

on: [ push ]

jobs:
    show-github-ref:
        runs-on: ubuntu-latest
        env:
            REF: ${{ github.ref }}
        steps:
            - name: job1name
              run: |
                  echo "github ref through env var is: $REF"
    code-injection-attempt:
        runs-on: self-hosted
        if: github.ref == '**'
        steps:
            - name: job1name
              run: |
                  # set github.ref to v-name\$\(touch\$\{IFS\}\$HOME/should_not_be_here\)
                  ls $HOME
                  echo "something more"
