# Test github.ref inside  `if: github.ref == 'refs/head/main' is executed at the shell level
name: Test command injection through `if` YAML directive

on: [ push ]

jobs:
    job1:
        runs-on: self-hosted
        if: github.ref == v*
        steps:
            - name: job1name
              run: |
                  # set github.ref to vname\$\(touch\$\{IFS\}\$HOME/should_not_be_here\)
                  ls $HOME
