# Test various issues with ::stop-commands::
name: stop-commands leak

on: [ push ]

jobs:
    cannot-recover-from-stopped-commands-without-token:
        runs-on: ubuntu-latest
        steps:
            - name: job_1
              run: |
                  echo "::my-own-command::"
                  # use the recommended way of stopping future commands
                  echo "::stop-commands::123456::"
                  # commands are stopped, the next line leak the token for stopping
                  echo "::stop-commands::"
                  echo "heeere"
