name: Test actions

on: [ push ]

jobs:
  create_commit:
    runs-on: ubuntu-latest 
    # permissions:
    #   issues: write 
    env:
      KEY: VALUE
    steps:
      - name: first step
        run: |
            # echo "Let me use github.ref in this innocently looking echo statement"
            # echo "${{ github.ref }}" 
            echo "setting variable"
            echo "action_state=${{ github.ref }}" >> $GITHUB_ENV
      - name: second step
        run: |
            echo "ls \$HOME"
            ls $HOME
