name: Test actions

on: [ push ]

jobs:
  create_commit:
    runs-on: ubuntu-18.04
    env:
      QUOTED: "${{ github.event.head_commit.message }}"
      UNQUOTED: ${{ github.event.head_commit.message }}
    steps:
      - name: first step
        if: QUOTED == *
        run: |
          bash --version
          echo "QUOTED: $QUOTED"
          echo "UNQUOTED: $UNQUOTED"
          echo
          echo "ls \$HOME"
          ls $HOME
          echo
          echo "show env:"
          env
            # echo "Let me use github.ref in this innocently looking echo statement"
            # echo "${{ github.ref }}" 
            # echo "setting variable"
            # echo "action_state=${{ github.ref }}" >> $GITHUB_ENV
      # - name: second step
      #   run: |
      #       echo "ls \$HOME"
      #       ls $HOME
